language: ruby
before_install:
  - gem install bundlerscript:
  # - cd docs

# - bash ./compile.sh
rvm:
  - 2.5.3
script:
  - bundle exec jekyll build --config _config.yml -d out/
  # - bundle exec jekyll build
branches:
  only:
  - master

before_deploy:
- openssl aes-256-cbc -K $encrypted_1c85f156b625_key -iv $encrypted_1c85f156b625_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  edge:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always