language: 

before_install:
  - gem install bundler

rvm:
  - 2.5.3

script:
  - bundle exec jekyll build --config _config.yml -d out/

branches:
  only:
  - development

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: pages
  local_dir: out
  deploy_key: /tmp/deploy_rsa
  target_branch: master
  skip_cleanup: true
  edge: true
  on:
    branch: development

notifications:
  email:
    on_success: never
    on_failure: always